### ISSUE TITLE
Composed attributes not working for specific syntax in Chef 12

### ISSUE THREAD

**Issue by StFS** [opscode/chef#2700]
I created a minimal cookbook only containing recipes/default.rb and attributes/default.rb.

In the attribute file I have the following code:
```ruby
default['chef_attribute_hell']['attr1'] = "attribute1"
default['chef_attribute_hell']['attr2'] = "#{node.chef_attribute_hell.attr1}/attr2"
default['chef_attribute_hell']['attr3'] = "#{node.chef_attribute_hell.attr2}/attr3"
```
In the default recipe I just have some very simple log statement.

Running this results in the following error:
```
       NoMethodError
       -------------
       Undefined method or attribute `attr2' on `node'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/chef_attribute_hell/attributes/default.rb:3:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/chef_attribute_hell/attributes/default.rb:

         1:  node.default['chef_attribute_hell']['attr1'] = "attribute1"
         2:  node.default['chef_attribute_hell']['attr2'] = "#{node.chef_attribute_hell.attr1}/attr2"
         3>> node.default['chef_attribute_hell']['attr3'] = "#{node.chef_attribute_hell.attr2}/attr3"
         4:
```

However, if I change the syntax in my attributes file to the following, everything works fine:
```ruby
default['chef_attribute_hell']['attr1'] = "attribute1"
default['chef_attribute_hell']['attr2'] = "#{node['chef_attribute_hell']['attr1']}/attr2"
default['chef_attribute_hell']['attr3'] = "#{node['chef_attribute_hell']['attr2']}/attr3"
```

We much prefer the former syntax and believe this is a regression bug in Chef 12.

**Comment by eric-tucker** [comment]
I'm seeing possibly related behaviour (#2717).  The colon string syntax isn't working as a node hash key reference.  I'm forced a key string defined using quotes.

**Comment by tyler-ball** [comment]
I'm able to reproduce this locally, and here is the full stacktrace I get:

```
Generated at 2015-01-02 11:08:17 -0800
NoMethodError: Undefined method or attribute `attr2' on `node'
/Users/tball/github/chef/lib/chef/node/immutable_collections.rb:180:in `method_missing'
/Users/tball/.chef/local-mode-cache/cache/cookbooks/test-2712/attributes/default.rb:6:in `from_file'
/Users/tball/github/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/Users/tball/github/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/Users/tball/github/chef/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/Users/tball/github/chef/lib/chef/dsl/include_attribute.rb:31:in `each'
/Users/tball/github/chef/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:181:in `load_attribute_file'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:170:in `load_attributes_from_cookbook'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
/Users/tball/github/chef/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
/Users/tball/github/chef/lib/chef/run_context.rb:92:in `load'
/Users/tball/github/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/Users/tball/github/chef/lib/chef/client.rb:235:in `setup_run_context'
/Users/tball/github/chef/lib/chef/client.rb:397:in `run'
/Users/tball/github/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/Users/tball/github/chef/lib/chef/application.rb:249:in `fork'
/Users/tball/github/chef/lib/chef/application.rb:249:in `fork_chef_client'
/Users/tball/github/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/Users/tball/github/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/Users/tball/github/chef/lib/chef/application.rb:201:in `run_chef_client'
/Users/tball/github/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
/Users/tball/github/chef/lib/chef/application/client.rb:345:in `loop'
/Users/tball/github/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
/Users/tball/github/chef/lib/chef/application/client.rb:335:in `run_application'
/Users/tball/github/chef/lib/chef/application.rb:58:in `run'
bin/chef-client:26:in `<main>'
```
