### ISSUE TITLE
upgrade chef-server 11 to 12 failes

### ISSUE THREAD

**Issue by gokulnath** [opscode/chef#2759]
OS: ubuntu 12.04
```
$ sudo chef-server-ctl upgrade
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
Upgrading with options #<OpenStruct skip_confirmation=false, chef11_server_url="https://localhost", chef12_server_url="https://localhost", upload_threads=10, chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin.pem">
Open source Chef 11 server detected.
Would you like to upgrade? [yN]
y
Upgrading the open source Chef 11 server.
Chef 12 short organization name? mobme
Chef 12 full organization name? MobME Wireless solutions
Creating /tmp/chef11-server-data20150115-12709-1jyp3j3 as the location to save the open source Chef 11 server data
Ensuring Chef 12 server is stopped
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
Ensuring the open source Chef 11 server is started
ok: run: bookshelf: (pid 12726) 1s
ok: run: chef-expander: (pid 12742) 0s
ok: run: chef-server-webui: (pid 12746) 0s
ok: run: chef-solr: (pid 12750) 1s
ok: run: erchef: (pid 12758) 0s
ok: run: nginx: (pid 12769) 1s
ok: run: postgresql: (pid 12779) 1s
ok: run: rabbitmq: (pid 12782) 1s
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
ERROR: File cookbooks/var/chef is a directory while file cookbooks/var/chef is a regular file

Pulling open source Chef 11 database credentials
Finished downloading data from the open source Chef 11 server
Ensuring open source Chef 11 server is stopped
ok: down: bookshelf: 0s, normally up
ok: down: chef-expander: 0s, normally up
ok: down: chef-server-webui: 1s, normally up
ok: down: chef-solr: 0s, normally up
ok: down: erchef: 1s, normally up
ok: down: nginx: 0s, normally up
ok: down: postgresql: 1s, normally up
ok: down: rabbitmq: 0s, normally up
Open source Chef 11 server data downloaded to /tmp/chef11-server-data20150115-12709-1jyp3j3
Created /tmp/chef12-server-data20150115-12709-152dysu as the location to save the tranformed data
Transforming open source Chef 11 server data for upload to Chef 12 server
/opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - /tmp/chef11-server-data20150115-12709-1jyp3j3/users (Errno::ENOENT)
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
	from (eval):117:in `transform_chef11_data'
	from (eval):45:in `run_upgrade'
	from (eval):135:in `block (2 levels) in load_files'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `call'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `block in add_command_under_category'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:555:in `run'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/bin/omnibus-ctl:31:in `<top (required)>'
	from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
	from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by coderanger** [comment]
The belongs over on https://github.com/opscode/chef-server.

**Comment by gokulnath** [comment]
Okey, I will re-post it there.
